### PR TITLE
fix: insert slotting after first post

### PR DESCRIPTION
**Pull request by DerZade**
It probably needs some styling to make it pretty and stand out, but I'm not a designer.

### CODE REVIEW

**Comment by Fusselwurm** [comment]
https://forum2.gruppe-adler.de/topic/3141/2023-04-10-mo-operation-evening-light-kunduz-gm-main-modset-update

```
Uncaught (in promise) ReferenceError: topicNode is not defined
```

**Comment by DerZade** [comment]
> https://forum2.gruppe-adler.de/topic/3141/2023-04-10-mo-operation-evening-light-kunduz-gm-main-modset-update
> 
> ```
> Uncaught (in promise) ReferenceError: topicNode is not defined
> ```

Should be fixed with c08f015

**Comment by Fusselwurm** [comment]
> > https://forum2.gruppe-adler.de/topic/3141/2023-04-10-mo-operation-evening-light-kunduz-gm-main-modset-update
> > ```
> > Uncaught (in promise) ReferenceError: topicNode is not defined
> > ```
> 
> Should be fixed with [c08f015](https://github.com/gruppe-adler/nodebb-plugin-arma3-slotting/commit/c08f0156a2786e9a2d38939a3977ae7836711322)

I get different errors now. Is it just me? Did you actually test this on your machine?

**Comment by DerZade** [comment]
> I get different errors now. Is it just me? Did you actually test this on your machine?

Nope I did not. Tbh I'm just amazed that this is not pushed to prod immediately. I thought that's how things get tested here nowadays.

**Comment by DerZade** [comment]
But just to prove my point:

**Comment by Fusselwurm** [comment]
works in production, cant reproduce

**Review by Fusselwurm — APPROVED** [review]

**Pull request merged**
