### PR TITLE
change slotliste height from 20 to 80 depending on toggle

### PR DESCRIPTION
**Pull request by nomisum**

### CODE REVIEW

**Comment by Fusselwurm** [comment]
:thinking: toggle stops working with these changes.

**Comment by nomisum** [comment]
@Fusselwurm can you try again with the new changes?

**Comment by Fusselwurm** [comment]
doesnt work... at all. lets go over this together sometime 🤔

**Comment by Fusselwurm** [comment]
Screenshot_20230325_121501
Screenshot_20230325_121446

**Pull request merged**
